import './assets/css/main.css'
import type { Metadata } from 'next'
import Navigation from './components/Navigation'
import { ReduxProvider } from './reduxProvider'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body>
          <div className="bg-white">
            <slot name="header" >
                <Navigation />
            </slot>
          </div>
          {children}
          <slot name="footer" >
            {/* <LayoutsNotification /> */}
            <Footer />
          </slot>
        </body>
      </html>
    </ReduxProvider>
  )
}
