import type { Metadata } from "next";
import Navigation from "../components/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <div className="bg-white">
        <slot name="header">
          <Navigation />
        </slot>
        <slot />
        {/* <slot name="footer" >
                <LayoutsNotification />
                <LayoutsDefaultFooter />
            </slot> */}
      </div>
      <h1>CHECK THIS OUT</h1>
      {children}
    </section>
  );
}
